### PR TITLE
fix: Swap to github pages for security alert

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@MaryBethBaker @RachelMuston @jmealing is this repo still being used or should it get archived?
Just patching this since it shows up under the GitHub security alerts

**Comment by MaryBethBaker** [comment]
Hi @nschonni,

I am not currently using this repo, but I just got back into the office, so I will check with my colleagues before we make any decisions about archiving. 

Mary Beth

//cc @jmealing  @wendyliao2018

**Comment by jmealing** [comment]
Hi @nschonni - I am not using this repo.

**Comment by nschonni** [comment]
No worries, I won't archive anything before you folks confirm. Also, if you decide later, you can un-archive as well.

**Comment by MaryBethBaker** [comment]
Thanks @nschonni We'll do our best to get back to this project with a decision to archive shortly.

And congrats on your work in the Open Source file, not sure if it means a new posting/role/department. I saw something come through today on GCCollab about the community.

**Comment by nschonni** [comment]
Yup, just over at TBS on a secondment for a bit

**Comment by MaryBethBaker** [comment]
We've decided to archive this repository. I'm going to close this thread and archive the work. Thanks @nschonni for the assistance/heads up about this repository.

**Pull request closed without merging**
